# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DrawingToday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # UI
  pod 'SnapKit'

  # Firebase
  pod 'Firebase/Analytics'

  # UI
  pod 'SwiftLint'

  # Pods for DrawingToday

end
